import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: dailyRetros } = api.dailyRetros.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            BJJ Companion
          </h1>
          <div className="grid grid-cols-1 gap-4 md:gap-8">
            {dailyRetros &&
              dailyRetros.map((retro) => (
                <div
                  key={retro.id}
                  className="flex flex-col gap-8 rounded border border-white p-8"
                >
                  <div className="text-2xl font-bold text-white">
                    {`${retro.date.toLocaleDateString()} Retrospective`}
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-white">Went Well</h3>
                    <span className="text-white">{retro.wentWell}</span>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-white">Went Wrong</h3>
                    <span className="text-white">{retro.wentWrong}</span>
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-white">To Improve</h3>
                    <span className="text-white">{retro.toImprove}</span>
                  </div>
                </div>
              ))}
          </div>
          <p className="text-2xl text-white">By @roacfe</p>
        </div>
      </main>
    </>
  );
};

export default Home;
